# fly.toml app configuration file generated for discord-hook on 2024-07-01T16:31:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-hook'
primary_region = 'nrt'

[http_service]
  internal_port = 3000

[[vm]]
  size = 'shared-cpu-1x'
  memory = "256mb"
