name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up Flyctl
        uses: superfly/flyctl-action@1.1
        with:
          api_token: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          fly deploy --config fly.toml
