name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DRUG_URL : ${{secrets.DRUG_URL}}
  GONGMO_URL : ${{secrets.GONGMO_URL}}
  HOTDEAL_URL : ${{secrets.HOTDEAL_URL}}
  REDIS_URL : ${{secrets.REDIS_URL}}
  TEST : ${{secrets.TEST}}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy
